<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
	'Partnership' => 'Партнерская программа',
	'Login' => 'Логин',
	'Enter' => 'Вход',
	'Registration' => 'Регистрация',
	'Admin-stuff' => 'Администрация',
	'Users' => 'Пользователи',
	'Permissions' => 'Права доступа',
	'Partners' => 'Партнеры',
	'Shop' => 'Магазин',
	'Catalog' => 'Каталог',
	'Cart' => 'Корзина',
	'Order list' => 'Список заказов',
	'Wholesale orders' => 'Заказы на опт.',
	'Items counter' => 'Кол-во просмотров',
	'Content' => 'Контент',
	'Menu' => 'Меню',
	'Static content' => 'Статичный контент',
	'News' => 'Новости',
	'Slider' => 'Слайдер',
	'Notifications' => 'Уведомления',
	'Open cart' => 'Открыть корзину',
];
