<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
	'You have not permissions!' => 'У вас нет прав!',
	'Record is created!' => 'Запись добавлена!',
	'Record is added!' => 'Запись добавлена!',
	'Record is updated!' => 'Запись обновлена!',
	'Record is deleted!' => 'Запись удалена!',
	'Records are deleted!' => 'Записи удалены!',
	'Failure!' => 'Ошибка!',
	'Is not ajax!' => 'Это не ajax!',
	'The requested page does not exist!' => 'Страница не существует!',
	'► Confirm of registration' => '► Подтверждение регистрации',
	'► New refferal!' => '► Новый Реферал!',
	'You registered! Confirm of registration is sent to your email.' => 'Вы зарегистрированы! Подверждение регистрации отправлено вам на почту.',
	'You are registered!' => 'Вы уже зарегистрированы!',
	'You have passed confirmation!' => 'Вы прошли проверку!',
	'This email is registered!' => 'Пользователь с данным email адресом не зарегистрирован!',
	'This user is not existed!' => 'Такого пользователя нет!',
	'This menu is exist!' => 'Такое меню уже существует!',
	'This url is exist!' => 'Такой url уже существует!',
	'Fill the field!' => 'Заполните поле!',
	'Please, fill this field!' => 'Пожалуйста, заполните поле!',
	'This module is existed!' => 'Этот модуль существует!',
	'In this field minimum acceptable symbols are 2!' => 'В этом поле минимально допустимое количество символов 2!',
	'In this field maximal acceptable symbols are 100!' => 'В этом поле максимально допустимое количество символов 100!',
	'In this field maximal acceptable symbols are 255!' => 'В этом поле максимально допустимое количество символов 255!',
	'Incorrect symbols!' => 'Неправильные символы!',
	'New password is sent to your email!' => 'Новый пароль уже выслан на ваш email!',
	'Subject: Password restoration' => 'Тема: Восстановления пароля',
	'Password is changed!' => 'Пароль изменен!',
	'This field must be filling!' => 'Это поле должно быть заполнено!',
	'Incorrect characters are entered!' => 'Введенны неправильные символы!',
	'Incorrect date is entered!' => 'Введена неправильная дата!',
	'No items in cart!' => 'Корзина пуста!',
	'Order is created!' => 'Заказ оформлен!',
	'Added in favourites!' => 'Добавлено в избранное!',
	'Profile is updated!' => 'Профиль обновлен!',
	'Order can not be made! You must fill your profile!' => 'Заказ не может быть оформлен! Вы должны заполнить свой профиль!',
	'Wrong password or login!' => 'Неправильный пароль или логин!',
];
